import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";

import SectionCards from "@/components/card/SectionCards";
import {
  VideoTypes,
  getPopularVideos,
  getVideos,
  getWatchItAgainVideos,
} from "@/lib/videos";
import UseRedirectUser from "@/utils/redirectUser";

interface Props {
  movieVid: VideoTypes[];
  musicVid: VideoTypes[];
  popularVid: VideoTypes[];
  watchItAgainVideos: VideoTypes[];
}

export default function Home({
  movieVid,
  musicVid,
  popularVid,
  watchItAgainVideos,
}: Props) {
  return (
    <>
      <Head>
        <title>Viewflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Banner
          title="my movie title"
          subTitle="my movie subtitle"
          imgUrl="/static/mountains.jpg"
          videoId="4zH5iYM4wJo"
        />

        <SectionCards
          title="movies"
          size="large"
          shouldScale
          videos={movieVid}
        />

        {watchItAgainVideos.length > 0 && (
          <SectionCards
            title="Watch it again"
            size="small"
            shouldScale
            videos={watchItAgainVideos}
          />
        )}

        <SectionCards
          title="music"
          size="small"
          shouldScale
          videos={musicVid}
        />

        <SectionCards
          title="popular"
          size="medium"
          shouldScale
          videos={popularVid}
        />
      </div>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { userId, token } = await UseRedirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }

  const movieVid = await getVideos("movies");
  const musicVid = await getVideos("music");
  const popularVid = await getPopularVideos();

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  return {
    props: {
      movieVid: movieVid ? movieVid : [],
      musicVid: musicVid ? musicVid : [],
      popularVid: popularVid ? popularVid : [],
      watchItAgainVideos: watchItAgainVideos ? watchItAgainVideos : [],
    },
  };
}
