import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import NavBar from "@/components/nav/Navbar";
import Card from "@/components/card/Card";
import SectionCards from "@/components/card/SectionCards";
import { VideoTypes, getPopularVideos, getVideos } from "@/lib/videos";

interface Props {
  movieVid: VideoTypes[];
  travelVid: VideoTypes[];
  productivityVid: VideoTypes[];
  popularVid: VideoTypes[];
}

export default function Home({
  movieVid,
  travelVid,
  productivityVid,
  popularVid,
}: Props) {
  return (
    <>
      <Head>
        <title>Viewflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <NavBar />
        <Banner
          title="my movie title"
          subTitle="my movie subtitle"
          imgUrl="/static/mountains.jpg"
          videoId="my movie video"
        />

        <SectionCards
          title="movies"
          size="large"
          shouldScale
          videos={movieVid}
        />
        <SectionCards
          title="travel"
          size="small"
          shouldScale
          videos={travelVid}
        />
        <SectionCards
          title="productivity"
          size="medium"
          shouldScale
          videos={productivityVid}
        />
        <SectionCards
          title="popular"
          size="small"
          shouldScale
          videos={popularVid}
        />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const movieVid = await getVideos("movies");
  const travelVid = await getVideos("travel");
  const productivityVid = await getVideos("productivity");
  const popularVid = await getPopularVideos();

  return {
    props: {
      movieVid: movieVid ? movieVid : [],
      travelVid: travelVid ? travelVid : [],
      productivityVid: productivityVid ? productivityVid : [],
      popularVid: popularVid ? popularVid : [],
    },
  };
}
