import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";

import SectionCards from "@/components/card/SectionCards";
import { VideoTypes, getPopularVideos, getVideos } from "@/lib/videos";

interface Props {
  movieVid: VideoTypes[];
  musicVid: VideoTypes[];
  // seriesVid: VideoTypes[];
  popularVid: VideoTypes[];
  session: any;
}

export default function Home({
  movieVid,
  musicVid,
  // seriesVid,
  popularVid,
}: Props) {
  return (
    <>
      <Head>
        <title>Viewflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Banner
          title="my movie title"
          subTitle="my movie subtitle"
          imgUrl="/static/mountains.jpg"
          videoId="4zH5iYM4wJo"
        />
        <SectionCards
          title="movies"
          size="large"
          shouldScale
          videos={movieVid}
        />
        <SectionCards
          title="music"
          size="small"
          shouldScale
          videos={musicVid}
        />
        {/*   <SectionCards
          title="series"
          size="medium"
          shouldScale
          videos={seriesVid}
        /> */}
        <SectionCards
          title="popular"
          size="small"
          shouldScale
          videos={popularVid}
        />
      </div>
    </>
  );
}

export async function getServerSideProps(context: Object) {
  const movieVid = await getVideos("movies");
  const musicVid = await getVideos("music");
  // const seriesVid = await getVideos("series");
  const popularVid = await getPopularVideos();

  return {
    props: {
      movieVid: movieVid ? movieVid : [],
      musicVid: musicVid ? musicVid : [],
      // seriesVid: seriesVid ? seriesVid : [],
      popularVid: popularVid ? popularVid : [],
    },
  };
}
